# Dockerfile.airflow
#FROM apache/airflow:3.1.7-python3.11

# Установка системных зависимостей (требуется для clickhouse-driver)
#USER root
#RUN apt-get update && \
#    apt-get install -y --no-install-recommends \
#        gcc \
#        g++ \
#        python3-dev \
#        && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/*

# Переключаемся на airflow
#USER airflow

# Копируем файл зависимостей и устанавливаем их
#COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

# Проверка установки (опционально)
#RUN pip list | grep -E "(airflow|clickhouse|kafka)"

FROM apache/airflow:3.1.7
ADD requirements.txt .
RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt
